entrada_bloqueada = room_speed * 0.25;
audio_room_enter("menu");
audio_menu_iniciar(0.38);
clique_iniciado = false;
menu_saida_timer = -1;
menu_timer = 0;
menu_destino = rm_menu_fases;
botao_hover = -1;
botao_x = 792;
botao_y = [196, 268, 340, 412];
botao_texto = ["JOGAR", "OPÇÕES", "CRÉDITOS", "SAIR"];
botao_sprite = [spr_menu_btn_jogar, spr_menu_btn_opcoes, spr_menu_btn_creditos, spr_menu_btn_opcoes];
botao_room = [rm_menu_fases, rm_menu_opcoes, rm_creditos, -1];
botao_hover_anterior = -1;
menu_saindo_jogo = false;
global.menu_reverso = false;
menu_bg_layer = layer_get_id("Backgrounds_1");
som_luz_id = audio_play_sfx(snd_menu_luz, 0, true);
som_natureza_id = audio_play_sfx(snd_menu_natureza, 0, true);
audio_gain_sfx(som_luz_id, 0.34, 0);
audio_gain_sfx(som_natureza_id, 0.46, 0);
