entrada_bloqueada = room_speed * 0.25;
clique_iniciado = false;
menu_saida_timer = -1;
menu_timer = 0;
menu_destino = rm_menu_fases;
botao_hover = -1;
botao_x = 794;
botao_y = [206, 288, 370];
botao_sprite = [spr_menu_btn_jogar, spr_menu_btn_opcoes, spr_menu_btn_creditos];
botao_room = [rm_menu_fases, rm_menu_opcoes, rm_creditos];
menu_bg_layer = layer_get_id("Backgrounds_1");
som_luz_id = audio_play_sound(snd_menu_luz, 0, true);
som_natureza_id = audio_play_sound(snd_menu_natureza, 0, true);
audio_sound_gain(som_luz_id, 0.34, 0);
audio_sound_gain(som_natureza_id, 0.46, 0);
